# Generated by Django 2.0.7 on 2018-07-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forward_func(apps, schema_editor):
    # 모든 유저에 대해서 프로파일 만들어줍니다.
    #apps.get_model('auth', 'User')
    # 위와 같은 형태가 되어야 동작한다. 아래와 같이 해보자
    auth_user_model = settings.AUTH_USER_MODEL.split('.') #auth.User를 튜플('auth', 'user')로 바꾸고
    #apps.get_model(auth_user_model[0], auth_user_model[1]) #이렇게 해도 되지만...
    User = apps.get_model(*auth_user_model) #이렇게 unpacking 하면 됨
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        print('create profiel for user#{}'.format(user.pk))
        Profile.objects.create(user=user)


def backward_func(apps, schema_editor):
    # 따로 해줄게 없다. 테이블을 날릴테니까
    pass

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_device_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ManyToManyField(to='blog.Device')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forward_func, backward_func),
    ]
