# Generated by Django 2.0.7 on 2018-07-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clinic_name',
            field=models.CharField(choices=[('WONJANG', '원장'), ('MARKETING', '마케팅담당자'), ('STAFF', '병원관계자')], default='MARKETING', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
