# Generated by Django 2.0.7 on 2018-07-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180722_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='clinic_name',
            new_name='clinicname',
        ),
    ]
