# Generated by Django 2.0.7 on 2018-07-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_device_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='content_url',
            new_name='contenturl',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('MARKETING', '마케팅'), ('CLINICAL', '임상')], default='MARKETING', max_length=20),
        ),
    ]
