# Generated by Django 2.0.7 on 2018-07-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180721_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('M', '마케팅'), ('C', '임상')], default='M', max_length=1),
        ),
    ]
