# Generated by Django 2.0.7 on 2018-07-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180724_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('maker', 'id')},
        ),
        migrations.AddField(
            model_name='device',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.Maker'),
            preserve_default=False,
        ),
    ]
