# Generated by Django 2.0.7 on 2018-08-06 15:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180806_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AlterField(
            model_name='resource',
            name='contenturl',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
